### ISSUE TITLE
Update/Add Support Link

### ISSUE THREAD

**Issue by imadarai** [w3f/polkadot-registrar-challenger#28]
The following changes were requested by @michalisFr and when I tried to make a PR - I realize I don't have the write access on this repo. Please either provide the write access or make the following changes. 

---------

<img width="787" alt="Screenshot 2021-12-09 at 4 28 08 PM" src="https://user-images.githubusercontent.com/57454832/145579652-e2369089-34f1-44f2-88d9-0d992cb7fec9.png">

Let's add this:
`For instructions on how to use this page, visit our <a href="https://support.polkadot.network/support/solutions/articles/65000179747-how-to-use-the-w3f-registrar-page" target="_blank">Support page</a>.`
after this sentence:
`A full guide is available in our Polkadot Wiki, respectively how to request judgement.`

And in the Footer let's change Email Support to:
`Support: support.polkadot.network (https://support.polkadot.network/support/solutions/articles/65000179747-how-to-use-the-w3f-registrar-page)`
linking to the same article.

----------
cc: @lamafab

**Comment by lamafab** [comment]
Thanks, changes are now live -> https://registrar.web3.foundation/

**Comment by imadarai** [comment]
@lamafab Thanks!!! 

Not trying to nit-picky here but the first link opens in new tab, while the one in the footer opens in the same window.  If we are following the convention, all external links should open in the new window :-) 

Thanks a million @lamafab !!

**Comment by lamafab** [comment]
@imadarai Yep, done. I didn't notice it before because I *always* open all links in a new tab by using the middle click.
