### ISSUE TITLE
Add verification method for websites in identity

### ISSUE THREAD

**Issue by zedazicapital** [w3f/polkadot-registrar-challenger#82]
Currently web entry is not supported by automatic W3F-registrar. Websites is one of the top priority for the validators to receive new nominators what I have read.
Verification challenge could be as easy as adding an TXT record to DNS with the challenge code to proof the ownership of the domain name.

**Comment by lamafab** [comment]
Hi, so right now we just verify websites manually. The TXT approach would work, but often people put in their LinkedIn, Github, social media, etc where they don't have control over the domain. Given that manual requests for websites don't occur often, we'll leave it as is unless the situation changes.

> Websites is one of the top priority for the validators to receive new nominators what I have read.

If you're referring to the 1kv programme, that's not the case. Website does not need to be provided, you just need a valid identity (which largely can be verified in an automated manner). If you want to a website, just ask for manual verification as can be seen on https://registrar.web3.foundation/
