### ISSUE TITLE
Build does not work

### ISSUE THREAD

**Issue by Petar-23** [w3f/polkadot-registrar-challenger#95]
If I execute the build command `cargo build --bin registrar-bot --release` I get the following error:

`error: no bin target named 'registrar-bot' `

I'm very thankful for any help on this topic :D

**Comment by Nexus2k** [comment]
There's no build target registrar-bot... you have to use registrar instead.

**Comment by lamafab** [comment]
From the Readme:

`$ cargo run --release --bin registrar`
